---
title: "Fichiers au format ods"
author: "NK & SG"
date: "octobre 2018"
output:
  html_document:
    theme: united
    toc: yes
    toc_depth: 4
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problématique

Manipuler des fichiers "tableurs" dans R, en particulier celui de Libre Office, Calc. L'objectif est de lire les données d'un fichier Calc dans une structure de données R, ou l'inverse, exporter des données R dans Calc


## Solution retenue

Convertir au préalable (via Calc par exemple) les fichiers **ods** au format **xlsx** et ensuite utiliser le package `openxlsx` pour la lecture et l'écriture.

> Le package `openxlsx` ne permet ni de lire ni d'écrire des fichiers au format **ods**.

## Particularité de syntaxe

Pour l'instant, aucune. 

## Exemples

Voir **thème 1 partie 3** sur la lecture et l'écriture de fichiers Excel au format **xlsx**.


## Solutions viables non retenues

Les packages `xlsx` et `XLConnect` sont des alternatives efficaces. Ils présentent le même inconvénient que le package `openxlsx` à savoir la nécessite de convertir le fichier en entrée au format **xlsx**.  

## Solutions à ne pas utiliser

Le package `readODS` n'est pas recommandé. La fonction `read_ods` de ce package permet de lire un fichier au format **ods**. La fonction `write_ods` ne fonctionne pas. De plus, le développement et la maintenance du package semblent interrompus : la dernière mise à jour remonte à fin 2016. 

## Niveau d'intégration à l'USSR

### Développements préconisés

La position de l'Insee est de favoriser l'utilisation du tableur libre Calc. À l'heure actuelle, aucune solution n'est complètement satisfaisante pour faire interagir Calc et **R**. Le développement d'un package spécifique à la lecture et l'écriture de fichier au format **ods** devrait être envisagé. Le package `readODS` pourrait être le point de départ de ce nouveau package. 

Le code du package `readODS` est disponible sur github : <https://github.com/chainsawriot/readODS>.

Les fonctionnalités envisagées et la syntaxe devraient équivalentes à celles disponibles dans le package `openxlsx`. 

### Points de vigilance

Le package `openxlsx` ne lit que les fichiers au format **xlsx**. Il faut donc convertir au préalable les fichiers **ods** à ce format. De plus, la robustesse de cette méthode est dépendante des mises à jours du format **xlsx** qui évolue régulièrement. Cela risque donc de créer des problèmes de compatibilité. 

## Intégration au dispositif de formation

La question est abordée dans la formation "Prise en main rapide de données sous R", lors de la séquence 9 ("formats de fichiers d'échange").





